// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN221_DinhChinh_Ass3.DataAccess.Repository;

#nullable disable

namespace PRN221_DinhChinh_Ass3.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241104095133_updatebookprice")]
    partial class updatebookprice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN221_DinhChinh_Ass3.Model.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<bool>("IsShipper")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("PRN221_DinhChinh_Ass3.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("PRN221_DinhChinh_Ass3.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Caterories");
                });

            modelBuilder.Entity("PRN221_DinhChinh_Ass3.Model.Ship", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateShip")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("UserShipId")
                        .HasColumnType("int");

                    b.HasKey("ShipId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserOrderId");

                    b.HasIndex("UserShipId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("PRN221_DinhChinh_Ass3.Model.Book", b =>
                {
                    b.HasOne("PRN221_DinhChinh_Ass3.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PRN221_DinhChinh_Ass3.Model.Ship", b =>
                {
                    b.HasOne("PRN221_DinhChinh_Ass3.Model.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("PRN221_DinhChinh_Ass3.Model.AppUser", "UserOrder")
                        .WithMany()
                        .HasForeignKey("UserOrderId");

                    b.HasOne("PRN221_DinhChinh_Ass3.Model.AppUser", "UserShip")
                        .WithMany()
                        .HasForeignKey("UserShipId");

                    b.Navigation("Book");

                    b.Navigation("UserOrder");

                    b.Navigation("UserShip");
                });
#pragma warning restore 612, 618
        }
    }
}
